language: python
dist: xenial

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r test-requirements.txt
  - pip install .

script:
  - pylint baudot/
  - coverage run --source baudot/ -m pytest tests/

after_success:
  - coverage report
